"""Event type constants for the colony simulation."""

# Event types Claude can choose from.
SELECTABLE_EVENT_TYPES = (
    "good_harvest",
    "poor_harvest",
    "construction",
    "illness",
    "dispute",
    "discovery",
    "quiet_day",
)

# Special event types generated by the engine, not selectable by Claude.
CHAOS_GODS_EVENT_TYPE = "chaos_gods"
FAILED_CONSTRUCTION_EVENT_TYPE = "failed_construction"

ALL_EVENT_TYPES = SELECTABLE_EVENT_TYPES + (
    CHAOS_GODS_EVENT_TYPE,
    FAILED_CONSTRUCTION_EVENT_TYPE,
)

# How many recent events to keep inline in state.json.
RECENT_EVENT_WINDOW = 5
